### ISSUE TITLE
Determine what support is needed for multiple scope names

### ISSUE THREAD

**Issue by duftler** [spinnaker/kayenta#193]
We now (or will soon) have support for configuring multiple scope names on a canary config via the Spinnaker ui.

The Canary stage configuration ui and orca's [RunKayentaCanaryTask](https://github.com/spinnaker/orca/blob/master/orca-kayenta/src/main/groovy/com/netflix/spinnaker/orca/kayenta/tasks/RunKayentaCanaryTask.groovy#L43) also have support for referencing a single scope name selected from all the scope names configured in the canary config.

However, if a canary config defines more than one scope name, the Spinnaker Canary stage configuration ui and the orca stage cannot be used to run the canary.

In order to properly support referencing multiple scope names, it seems what is really required is support for fully configuring a list of objects defining all of the scope information. That is, multiple blocks like this one (+ the scope name): 
![image](https://user-images.githubusercontent.com/8437718/34575947-5dc670be-f14a-11e7-88ad-3698e75276c3.png)

And the `RunKayentaCanaryTask` stage in orca would need to be updated to match.

If all users of multiple scope names are non-Spinnaker users, maybe this work doesn't need to happen right now. If they are Spinnaker users, we need to figure out if the lack of this support is a blocking issue, or can be considered an enhancement for after initial OSS release.

One shortcut might be to update orca to have full support, but not to update the Canary stage configuration ui. Then those users would have to edit that stage as json.

**Comment by skandragon** [comment]
Is this handled now, as kayenta supports multiple scopes?

**Comment by duftler** [comment]
Yup.
