### ISSUE TITLE
Implement per-metric NaN strategy

### ISSUE THREAD

**Issue by csanden** [spinnaker/kayenta#237]
To better support error metrics, we need to implement a per-metric NaN strategy. The current default strategy is to remove NaN values prior to classification. In the case of error metrics (Atlas), NaNs can represent the absence of an observation, i.e., no errors. 

### Proposed NaN Strategies
- Remove NaNs (default)
- Replace NaNs with Zeros

The user should be able to select one of the proposed NaN strategies when configuring the metric; the default value would be to remove NaN values.

**Comment by skandragon** [comment]
#298 as a PR.
