### ISSUE TITLE
Error Handling - Tied values fail canary analysis

### ISSUE THREAD

**Issue by e96wic** [spinnaker/kayenta#301]
I created an example metric that measures my container memory limit. If this does not change in one interval (which the limit usually does not), I get an error which is caused by [this](https://github.com/spinnaker/kayenta/blob/f704192fa8fb7beaf75d40c74ab85c680a404d33/kayenta-mannwhitney/src/main/scala/com/netflix/kayenta/mannwhitney/MannWhitney.scala#L93).

This is probably some kind of error handling problem - I would expect a proper result of a canary analysis using constant values.

**Comment by skandragon** [comment]
We actually discovered this recently as well, and have a fix planned.

**Comment by csanden** [comment]
This issue was fixed in #343.
