### ISSUE TITLE
Support InfluxDB as a metric source

### ISSUE THREAD

**Issue by joerajeev** [spinnaker/kayenta#311]
InfluxDB is a time series database that would be useful to support as a source of metrics
It is as popular as Datadog is : see [this comparison on trends](https://trends.google.com/trends/explore?q=%2Fm%2F0wfvvyq,%2Fg%2F11crxrq_2g)

**Comment by duftler** [comment]
Sounds good. If you're interested in doing the work to add this new metrics service, let me know and we can have a meeting so we can point you in the right direction. There is also a (as-yet-unshared) doc to guide you.

**Comment by joerajeev** [comment]
Hi @duftler, I have gone through the implementation for Datadog and started this. Happy to have a meeting and/or documentation to make sure I'm headed in the right direction.

**Comment by duftler** [comment]
gah, sorry, I missed your comments on this issue. Reviewing the PR now.
