### ISSUE TITLE
Canary stage failure cannot be ignored

### ISSUE THREAD

**Issue by e96wic** [spinnaker/kayenta#362]
I'm executing a regular spinnaker pipeline with a canary stage. When the canary stage fails, it terminates the whole pipeline even though 'ignore' is set. (By ignore I mean 'If stage fails > ignore the failure')

**Comment by duftler** [comment]
What version are you running?

This sounds like this issue that was fixed a while back: https://github.com/spinnaker/orca/pull/2230

**Comment by duftler** [comment]
Looks like the fix was released in 1.8.0.

**Comment by e96wic** [comment]
Ah, okay. Still running 1.7.

**Comment by duftler** [comment]
I did try this just now at head and it behaved as expected.
