### ISSUE TITLE
Allow custom queries

### ISSUE THREAD

**Issue by e96wic** [spinnaker/kayenta#363]
As a user, I'd like to be able to use custom queries with kayenta. By this I mean being able to compute values from different metrics, e.g. error rate -> failed_requests / total_requests.

**Comment by e96wic** [comment]
I'm using Prometheus. Can you quickly explain how this works?

**Comment by iiro** [comment]
We're using Datadog - and would need this one as well - actually for the the same use case as @e96wic has. @skandragon how would this work...?

**Comment by duftler** [comment]
We have some ideas on how this can be made to work in an elegant way. Experimenting with this now, and will post what we've come up with shortly.

**Comment by iiro** [comment]
@duftler any updates yet on this?

**Comment by duftler** [comment]
Am back to working on this now. Was mostly preparing for the Spinnaker Summit, so didn't have much time.

**Comment by duftler** [comment]
Backend support is here: https://github.com/spinnaker/kayenta/pull/400

**Comment by duftler** [comment]
This is fully supported for Prometheus and no further details have been provided w.r.t. what support the Datadog integration may be lacking.
