### ISSUE TITLE
Allow per-metric extended params

### ISSUE THREAD

**Issue by tillig** [spinnaker/kayenta#379]
When querying statistics from a Stackdriver source, [the default `perSeriesAligner` value for the stats is `ALIGN_MEAN`](https://github.com/spinnaker/kayenta/blob/99f472827eef5917cb39e69a2be01cb6ecbae854/kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/canary/StackdriverCanaryScope.java#L40). This works for some statistics types, but not all. For example, that works fine for a counter sort of metric but not so much for latency.

You can override this by specifying an extended parameter in the canary stage.

![Override aligner by using extended param](https://user-images.githubusercontent.com/1156571/45570043-3e5eed80-b816-11e8-9e80-ae797d90a8a4.png)

Unfortunately, that's a global setting for every stat in the whole canary stage, so again, if you override it the value will work for some stats but not all of them.

It would be helpful to allow per-statistic support for extended parameters so you can set up a single canary configuration that analyzes all the stats for a given run at one time. There's not a great workaround at the moment; you need different canary configurations based on statistic type and per-series aligner values which means you can't aggregate the stats and have the appropriate weight value relative to all of the other stats.

**Comment by tillig** [comment]
A concrete example of something that doesn't appear to be possible with Stackdriver that this would help: request latency analysis.

[This Netflix tech blog article](https://medium.com/netflix-techblog/automated-canary-analysis-at-netflix-with-kayenta-3260bc7acc69) shows a screen shot where latency gets analyzed based on a few different percentile values:

![Netflix latency in canary analysis](https://user-images.githubusercontent.com/1156571/45574411-d06df280-b824-11e8-925b-41b8fccc43a8.png)

In Stackdriver the `ALIGN_PERCENTILE_50` and `ALIGN_PERCENTILE_95` aligners aren't part of the stat query, they're part of the extended parameters - and you can currently only have one for the whole canary stage. It also doesn't appear Stackdriver has any way to provide directly accessible summary stats via a query. Like, I couldn't set up an automatically-calculated "50th percentile" stat that includes the aligner and boils it all down for use with Spinnaker.

**Comment by duftler** [comment]
Yup, this is a known problem. This bug: https://github.com/spinnaker/kayenta/issues/349 describes the same problem but for `resourceType`. I am moving all of those configurations from the canary stage config to the canary config as we speak.

**Comment by duftler** [comment]
Backend work is here: #381

**Comment by duftler** [comment]
Define the fields for the frontend (there is no UI support yet): https://github.com/spinnaker/deck-kayenta/pull/343

**Comment by duftler** [comment]
Frontend work for Stackdriver was submitted here: spinnaker/deck-kayenta#352
