### ISSUE TITLE
Consider automating code style enforcement

### ISSUE THREAD

**Issue by fieldju** [spinnaker/kayenta#481]
I noticed that code style comments come up a lot on PRs would something like
https://github.com/google/google-java-format and http://checkstyle.sourceforge.net/google_style.html to automatically enforce and correct code style enforcement be useful.

Close if this is not a good idea or too heavy handed.

**Comment by duftler** [comment]
I like the idea. Aligns with: https://github.com/spinnaker/spinnaker/issues/3504

**Comment by ttomsu** [comment]
Closing in favor of the referenced RFC issue
