### ISSUE TITLE
build/run issues in kayenta as stand-alone service  

### ISSUE THREAD

**Issue by amsin02** [spinnaker/kayenta#533]
Hi,

I want to run Kayenta as standalone service on windows. For that I have downloaded the code and I have been trying to build using "gradle build" command and run using "gradle run". Gradle run is failing with following exception - 

**Gradle Exception -** 
Execution failed for task ':kayenta-web:run'.
> A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_211\bin\java.exe''.

===============================================================
I have tried with creating jar and running it but that is also not working. Below is the error for same.

**Java -jar error -**
java -jar kayenta-web-1.5.0-SNAPSHOT.jar

no main manifest attribute, in kayenta-web-1.5.0-SNAPSHOT.jar

=============================================================
I have also tried to create image using Dockerfile but that is also failing. Below is the error that I am getting for **docker image build .** command.

**Docker error -**
Sending build context to Docker daemon 405.7 MB
Step 1/6 : FROM openjdk:8
 ---> bec43387959a
Step 2/6 : MAINTAINER delivery-engineering@netflix.com
 ---> Using cache
 ---> 7f87bc12ba02
Step 3/6 : COPY . workdir/
 ---> fd85a4bbf05c
Removing intermediate container 1abe07bb1c32
Step 4/6 : WORKDIR workdir
 ---> f2542082925e
Removing intermediate container 58ec1e6b737e
Step 5/6 : RUN GRADLE_USER_HOME=cache ./gradlew -I gradle/init-publish.gradle buildDeb -x test &&   dpkg -i ./kayenta-web/build/distributions/*.deb &&   cd .. &&   rm -rf workdir
 ---> Running in c41b42d9bada
/usr/bin/env: ‘sh\r’: No such file or directory
The command '/bin/sh -c GRADLE_USER_HOME=cache ./gradlew -I gradle/init-publish.gradle buildDeb -x test &&   dpkg -i ./kayenta-web/build/distributions/*.deb &&   cd .. &&   rm -rf workdir' returned a non-zero code: 127

Can somebody please share steps to build and run Kayenta on windows.

I have used following tools for this -
1. Java - JDK 1.8
2. Gradle - 4.7.
3. Docker version 17.03.1-ce-rc1, build 3476dbf

**Comment by fieldju** [comment]
@spinnakerbot assign-issue @fieldju

**Comment by fieldju** [comment]
Hello @amsin02, I run Kayenta as a standalone service via a fat jar.

To build the proper fatJar so that you can execute it as a jar, you need to run boot repackage.

`./gradlew jar bootRepackage`

This will have the proper manifests.

Once you have a fatJar, it is not as simple as calling `java -jar kayenta.jar`

You must pass a few [required system properties](https://github.com/spinnaker/kayenta/blob/master/kayenta-signalfx/kayenta-signalfx.gradle#L95).

```bash
java -Dspring.application.name=kayenta -Dspring.config.name=kayenta -Dspring.config.location=file:/path/to/your/kayenta-config.yaml -jar kayenta.jar
```

Here is a working config file from an integration test.

https://github.com/spinnaker/kayenta/blob/master/kayenta-signalfx/src/integration-test/resources/config/kayenta.yml

**Comment by fieldju** [comment]
Once you have it up and running you will have access to the up to date API docs via `http://localhost:8090/swagger-ui.html#/`

Not knowing much about your use case I would recommend you start with `/standalone_canary_analysis` for a UX similar to what Spinnaker provides via with canary analysis stage.

`standalone_canary_analysis` allows you to kick off a canary analysis execution with multiple canary judgements where it can fail fast if something is wrong.

`/canary` is also available and doesn't do anything other than call out to a metric source and compare 2 server groups for the provided time window.

You can see them both in action in these 2 rest assured API / integration tests

 1. [/canary - integration test](https://github.com/spinnaker/kayenta/blob/master/kayenta-signalfx/src/integration-test/java/com/netflix/kayenta/signalfx/EndToEndCanaryIntegrationTests.java)
1. [/standalone_canary_analysis - integration test](https://github.com/spinnaker/kayenta/blob/master/kayenta-signalfx/src/integration-test/java/com/netflix/kayenta/signalfx/EndToEndStandaloneCanaryAnalysisIntegrationTests.java)

I am working on a react app that will be OSS soon (tm) that will work will allow you to view results without having to read big un-human friendly JSON files. Similar to what deck provides but only for Kayenta.

**Comment by fieldju** [comment]
#411

**Comment by amsin02** [comment]
Hi @fieldju,

i tried to run *bootRepackage* but Build Failed saying:

*Task 'bootRepackage' not found in root project 'kayenta'*

===============================================================
i also tried to add  the following Spring Boot's new Gradle plugin in *build.gradle*

_buildscript {
    ext {
        springBootVersion = '2.0.0.BUILD-SNAPSHOT'
    }
    repositories {
        mavenCentral()
        maven { url 'https://repo.spring.io/libs-snapshot' }
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'_



i tried bootRun, bootjar, bootWar commands to make the executable jar file, still no luck.
saying 
*Task 'bootWar' not found in root project 'kayenta'*


=========================================================================

While with Docker,
*DockerImage* was built but it did not run even when the redis-server was up and running:

It threw several errors like:

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-05-19 10:38:18.927 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
.
.
.
.

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.q.redis.RedisQueue]: Factory method 'queue' threw exception; nested exception is redis.clients.jedis.exceptions.JedisConnectionException:
 Could not get a resource from the pool
.
.
.
.
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
.
.
.
.
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
.
.
.
.

Caused by: java.net.ConnectException: Connection refused (Connection refused)

**Comment by fieldju** [comment]
@amsin02, I forgot that they had removed the Springboot plugin. 

To build the fatJar Spinnaker/Kayenta you must create a [Gradle init script](https://docs.gradle.org/current/userguide/init_scripts.html#sec:init_script_plugins) that re-adds the plugin.

You will need to create the following file

init.gradle >>
```groovy
initscript {
  repositories {
    mavenCentral()
  }

  dependencies {
    classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.17.RELEASE")
  }
}

allprojects {
  apply plugin: org.springframework.boot.gradle.plugin.SpringBootPlugin
}
```

And you will build the fatjar via the following command

```bash
./gradlew --init-script path/to/init.gradle kayenta-web:bootRepackage
```

I am going to edit my above comment so that it reflect the fact that you have to use an init script.

**Comment by amsin02** [comment]
@fieldju , i created the **init.gradle**  file and ran the following command,

** ./gradlew --init-script init.gradle kayenta-web:bootRepackage **

AND BUILD FAILED Saying this:-

*Parallel execution is an incubating feature.
> Task :kayenta-mannwhitney:compileKotlin FAILED
> Task :kayenta-core:compileKotlin FAILED
> Task :kayenta-orca:compileKotlin FAILED

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-mannwhitney:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk-amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-core:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk-amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-orca:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk-amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

BUILD FAILED in 4m 24s
6 actionable tasks: 3 executed, 3 up-to-date

=================================================================

** I did set up java enviroment variable JAVA_HOME in the **
 /etc/profile and /etc/environment
 to
 ** /usr/lib/jvm/java-8-openjdk-amd64 **
still got the above error messages.

**Comment by fieldju** [comment]
@amsin02 

```
Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk-amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.
```

The answer is right there in the error message.
You have a Java Runtime Environment (JRE) installed you need an Java Development Kit (JDK)
You need to update your development environment and paths to point to an JDK.

**Comment by fieldju** [comment]
I just downloaded and installed the [Open JDK 8 MSI]( https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03/OpenJDK8U-jdk_x64_windows_hotspot_8u212b03.msi) from https://adoptopenjdk.net/ on my windows machine that I don't dev on.

I opened the regular windows cmd prompt.

git cloned this project, created the git init script and executed 

```
git clone https://github.com/spinnaker/kayenta.git
cd kayenta
vim init.gradle #pasting in contents from aboce
gradlew --init-script init.gradle kayenta-web:bootRepackage
java -jar kayenta-web/build/libs/kayenta-web.jar
```

```
C:\Users\Justin Field\kayenta>java -jar kayenta-web/build/libs/kayenta-web.jar
  __  __     ______     __  __     ______     __   __     ______   ______
 /\ \/ /    /\  __ \   /\ \_\ \   /\  ___\   /\ "-.\ \   /\__  _\ /\  __ \
 \ \  _"-.  \ \  __ \  \ \____ \  \ \  __\   \ \ \-.  \  \/_/\ \/ \ \  __ \
  \ \_\ \_\  \ \_\ \_\  \/\_____\  \ \_____\  \ \_\\"\_\    \ \_\  \ \_\ \_\
   \/_/\/_/   \/_/\/_/   \/_____/   \/_____/   \/_/ \/_/     \/_/   \/_/\/_/

2019-05-19 13:31:00.613  INFO 2456 --- [           main] com.netflix.kayenta.Main                 : Starting Main on DESKTOP-BDR0FK9 with PID 2456 (C:\Users\Justin Field\kayenta\kayenta-web\build\libs\kayenta-web.jar started by Justin Field in C:\Users\Justin Field\kayenta)
2019-05-19 13:31:00.621  INFO 2456 --- [           main] com.netflix.kayenta.Main                 : The following profiles are active: test,local
2019-05-19 13:31:01.115  INFO 2456 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4ccabbaa: startup date [Sun May 19 13:31:01 PDT 2019]; root of context hierarchy
```

```
C:\Users\Justin Field\kayenta>java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

C:\Users\Justin Field\kayenta>which java
/c/Program Files/AdoptOpenJDK/jdk-8.0.212.03-hotspot/bin/java

C:\Users\Justin Field\kayenta>echo %JAVA_HOME%
C:\Program Files\AdoptOpenJDK\jdk-8.0.212.03-hotspot\

C:\Users\Justin Field\kayenta>
```

**Comment by amsin02** [comment]
@fieldju ,
Thankyou for your help. It worked .

 I am trying to use kayenta as a standalone service without spinnaker with Prometheus as metric_store. I configured kayenta.yml with gcs as storage. Queries are not resolving though 
Response

**Comment by fieldju** [comment]
@amsin02 That sounds like a completely separate issue, please open a new issue or join the slack channel.

**Comment by rupsray** [comment]
I am also facing the same issue. Please help.

```
FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-azure:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-aws:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-google:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-influxdb:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-graphite:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-datadog:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-atlas:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kayenta-judge:compileScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
46 actionable tasks: 10 executed, 36 up-to-date
```
