### ISSUE TITLE
How configure for /standalone_canary_anaylis :: Getting identical Baseline and Canary Values 

### ISSUE THREAD

**Issue by amsin02** [spinnaker/kayenta#538]
I am trying to use kayenta **/standalone_canary-_analysis**  API for judgements ,But its Failing with unexpected error:

I tried with and without **lookBackMins**. This is my **executionRequest** -
{
  "executionRequest": {
    "analysisIntervalMins": 1,
    "beginAfterMins": 0,
    "lifetimeDurationMins": 10,
    "lookBackMins": 1,
    "scopes": [
      {
         "scopeName": "default",
        "controlScope": "control",
        "experimentScope": "experiment",
        "endTimeIso": "2019-05-23T11:30:00Z",
        "step": 15
      }
    ],
    "siteLocal": {},
    "thresholds": {
      "marginal": 95.0,
      "pass": 75.0
    }
  }
}

=================================================

This is the response i am getting at **/standalone_canary_analysis/{canaryExecutionId}** -
**Response**
{
  "application": "myapp",
  "user": "myapp",
  "pipelineId": "01DBHSRKA2EK0D4GVSXS3D1XT0",
  "stageStatus": [
    {
      "type": "setupAndExecuteCanariesStage",
      "name": "Sets up and executes the wait, run and monitor canary task chain.",
      "status": "TERMINAL"
    },
    {
      "type": "generateCanaryAnalysisResultStage",
      "name": "Aggregates and evaluates the canary executions and generates the final results.",
      "status": "TERMINAL"
    }
  ],
  "complete": true,
  "executionStatus": "TERMINAL",
  "exception": {
    "timestamp": 1558617070469,
    "exceptionType": "**NullPointerException**",
    "operation": "Sets up and executes the wait, run and monitor canary task chain.",
    "details": {
      "stackTrace": "java.lang.NullPointerException\r\n\tat com.netflix.kayenta.canaryanalysis.domain.**CanaryAnalysisExecutionRequest.getLookBackAsDuration**(CanaryAnalysisExecutionRequest.java:127)\r\n\tat com.netflix.kayenta.canaryanalysis.domain.CanaryAnalysisExecutionRequest.getLookBackAsInstant(CanaryAnalysisExecutionRequest.java:132)\r\n\tat com.netflix.kayenta.canaryanalysis.orca.stage.SetupAndExecuteCanariesStage.calculateStartAndEndForJudgement(SetupAndExecuteCanariesStage.java:251)\r\n\tat com.netflix.kayenta.canaryanalysis.orca.stage.SetupAndExecuteCanariesStage.lambda$buildRequestScopes$3(SetupAndExecuteCanariesStage.java:192)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat com.netflix.kayenta.canaryanalysis.orca.stage.SetupAndExecuteCanariesStage.buildRequestScopes(SetupAndExecuteCanariesStage.java:191)\r\n\tat com.netflix.kayenta.canaryanalysis.orca.stage.SetupAndExecuteCanariesStage.beforeStages(SetupAndExecuteCanariesStage.java:123)\r\n\tat com.netflix.spinnaker.orca.q.StageDefinitionBuildersKt.buildBeforeStages(StageDefinitionBuilders.kt:90)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:144)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)\r\n\tat com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:127)\r\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:59)\r\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:33)\r\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:68)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:55)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:65)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)\r\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)\r\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:48)\r\n\tat com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)\r\n\tat com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\n",
      "error": "Unexpected Task Failure",
      "errors": [
        null
      ]
    },
    "shouldRetry": false
  },
  "canaryAnalysisExecutionResult": {
    "didPassThresholds": false,
    "hasWarnings": false,
    "canaryScoreMessage": "There were no successful canary judgements to aggregate",
    "canaryScores": [],
    "canaryExecutionResults": []
  },
  "**canaryAnalysisExecutionRequest**": {
"scopes": [
      {
        "scopeName": "default",
        "controlScope": "control",
        "experimentScope": "experiment",
        "endTimeIso": "2019-05-23T11:30:00Z",
        "step": 15
      }
    ],
    "thresholds": {
      "pass": 75,
      "marginal": 95
    },
    "lifetimeDurationMins": 10,
    "beginAfterMins": 0,
    "analysisIntervalMins": 1,
     "lookBackMins" : 2,
    "siteLocal": {}
  },
  "**canaryConfig**": {
    "createdTimestamp": 1558534770,
    "updatedTimestamp": 1558596807437,
    "createdTimestampIso": "1970-01-19T00:55:34.770Z",
    "updatedTimestampIso": "2019-05-23T07:33:27.437Z",
    "name": "config-3",
    "description": "string",
    "configVersion": "v-2.0",
    "applications": [
      "myapp"
    ],
    "judge": {
      "name": "NetflixACAJudge-v1.0",
      "judgeConfigurations": {}
    },
    "metrics": [
      {
        "name": "control",
        "query": {
          "type": "prometheus",
          "metricName": "num_of_success_requests",
          "customFilter": "env=Baseline",
          "serviceType": "prometheus"
        },
        "groups": [
          "success_requests"
        ],
        "analysisConfigurations": {}
      },
      {
        "name": "experiment",
        "query": {
          "type": "prometheus",
          "metricName": "num_of_success_requests",
          "customFilter": "env=Canary",
          "serviceType": "prometheus"
        },
        "groups": [
          "success_requests"
        ],
        "analysisConfigurations": {}
      }
    ],
    "templates": {},
    "classifier": {
      "groupWeights": {
        "success_requests": 100
      },
      "scoreThresholds": {
        "pass": 75,
        "marginal": 95
      }
    }
  },
  "canaryConfigId": "72d4d15e-088b-466c-be83-02791c22fb11",
  "buildTimeMillis": 1558596832579,
  "buildTimeIso": "2019-05-23T07:33:52.579Z",
  "startTimeMillis": 1558596832597,
  "startTimeIso": "2019-05-23T07:33:52.597Z",
  "endTimeMillis": 1558596832744,
  "endTimeIso": "2019-05-23T07:33:52.744Z",
  "status": "terminal"
}

**Comment by fieldju** [comment]
@amsin02 did you figure this out? What was your issue?

**Comment by amsin02** [comment]
It was jst a variable issue 
It is lookbackMins
I was passing lookBackMins
