### ISSUE TITLE
How to set controlScope & experimentScope fields for /standalone_canary_analysis :: Getting identical Baseline & Canary Values

### ISSUE THREAD

**Issue by amsin02** [spinnaker/kayenta#539]
I am trying to use kayenta **/standalone_canary-_analysis**  API for judgements . I am using two instances of same application at **two different ports**, publishing metrics with labels {version="baseline", label="baseline", env ="baseline"} and {version="canary", label="canary", env ="canary"} respectively.

Things i have tried:
**controlScope="localhost:8019" & experimentScope="localhost:8020"
controlScope="baseline" & experimentScope="canary"
controlScope="control" & experimentScope="experiment"**

How to Set the configuration to get my baseline values from one instance and canary from the other ??

My Configuration 
```
{
  "canaryConfig": {
    "applications": [
      "myapp"
    ],
    "classifier": {
      "groupWeights": {
        "error_requests": 100.0
      },
    },
    "metrics": [
      {
        "name": "num_of_error_requests",
        "query": {
          "serviceType": "prometheus",
          "customInlineTemplate":"PromQL:(num_of_error_requests)",
          "type": "prometheus"
        },
        "scopeName": "default",
        "analysisConfigurations": {},
        "groups": [
          "error_requests"
        ]
      }
    ]
  },
  "executionRequest": {
    "analysisIntervalMins": 1,
    "beginAfterMins": 0,
    "lifetimeDurationMins": 1,
    "lookbackMins":0,
    "scopes": [
      {
        "controlScope": "control",
        "experimentScope": "experiment",
        "scopeName": "default",
        "step": 15
      }
    ]
  }
}
```

==========================================================

Response:

```
{
	"canaryExecutionResults": [{
			"results": [{
					"name": "num_of_error_requests",
					"tags": {
						"code": "[object Object]",
						"instance": "localhost:8019",
						"method": "GET",
						"label": "Baseline",
						"env": "Baseline",
						"job": "prometheus",
						"version": "Baseline"
					},
					"classification": "Pass",
					"classificationReason": "The Canary and Baseline data are identical",
					"groups": [
						"error_requests"
					]
				},
				{
					"name": "num_of_error_requests",
					"tags": {
						"code": "[object Object]",
						"instance": "localhost:8020",
						"method": "GET",
						"label": "Canary",
						"env": "Canary",
						"job": "prometheus",
						"version": "Canary"
					},
					"id": "32a8bb2f-c54c-4725-aa08-d79e142fef26",
					"classification": "Pass",
					"classificationReason": "The Canary and Baseline data are identical",
					"groups": [
						"error_requests"
					]
				}
			]
		},
		"canaryDuration": "PT1M"
	},
	"metricSetPairListId": "9cd57e4d-9b22-493a-90cc-f023bee742cd",
}]
}
}
```

**Comment by fieldju** [comment]
Can you make sure to enclose code blocks in triple "`" ticks so it is human readable. and have inline code be surround with single ticks.

The first thing I see is that you have different casing Control vs control in what you are publishing vs what you are requesting.

**Comment by fieldju** [comment]
![image](https://user-images.githubusercontent.com/711726/58342900-95d24600-7e06-11e9-9c08-0bebb189c47f.png)
 needs to match

![image](https://user-images.githubusercontent.com/711726/58342910-9e2a8100-7e06-11e9-9231-0da810076df8.png)

**Comment by amsin02** [comment]
Sorry , I didn't get you.
Should controlScope and experimentScope needs to be same??

**Comment by fieldju** [comment]
Please see my response to https://github.com/spinnaker/kayenta/issues/540

**Comment by fieldju** [comment]
@spinnakerbot assign-issue @fieldju

**Comment by amsin02** [comment]
Thanks for the help
