### ISSUE TITLE
Can I develop Azure cloud support for kayenta?

### ISSUE THREAD

**Issue by amsin02** [spinnaker/kayenta#556]
Hi @fieldju,

I am interested in developing **Azure cloud storage** support for Kayenta similar to google-gcs or amazon-s3 which Kayenta supports currently. Could you guide me, where to start?
As for using **Azure-Storage-SDK** via **maven** we need to add the following dependency:
```
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-storage-blob</artifactId>
	<version>11.0.1</version>
</dependency>
```

But, I am a bit lost regarding **where to add** this dependency or **which files to start with?**
coz, I didn't find any **pom.xml** file in Kayenta, so there must some way of introducing the dependencies similar to how it does for **amazonaws-SDK**.

I could add this dependency in **build.gradle** as:

```
dependencies {
    compile group: 'com.microsoft.azure', name: 'azure-storage-blob', version: '11.0.1'
}
```
 But, it doesn't seem the correct way of doing so as in build.gradle, i**t does not have any dependency written for google or aws.** 

Any help from anyone would be great!

**Comment by fieldju** [comment]
You need to add a new [sub-project](https://docs.gradle.org/current/userguide/multi_project_builds.html) to Kayenta that is [optionally enabled in the app config](https://github.com/spinnaker/kayenta/blob/master/kayenta-signalfx/src/integration-test/resources/config/kayenta.yml#L17) and implements [StorageService](https://github.com/spinnaker/kayenta/blob/master/kayenta-core/src/main/java/com/netflix/kayenta/storage/StorageService.java).

See:
- https://github.com/spinnaker/kayenta/blob/master/settings.gradle#L34
- https://github.com/spinnaker/kayenta/blob/master/kayenta-web/src/main/java/com/netflix/kayenta/Main.java#L63
- https://github.com/spinnaker/kayenta/blob/master/kayenta-web/kayenta-web.gradle#L32
- https://github.com/spinnaker/kayenta/blob/master/kayenta-s3/src/main/java/com/netflix/kayenta/s3/config/S3Configuration.java#L35
- https://github.com/spinnaker/kayenta/blob/master/kayenta-s3/src/main/java/com/netflix/kayenta/s3/storage/S3StorageService.java#L52
