### ISSUE TITLE
Orca is evaluating ${}-wrapped expressions which is meant for Prometheus.

### ISSUE THREAD

**Issue by amsin02** [spinnaker/kayenta#573]
Hey,
I am trying to use `customInlineTemplate` and `customFilterTemplate` for Prometheus Querying since they support direct **PromQL** syntax

```
"metrics": [{
		"name": "Number of Error Requests",
		"query": {
			"type": "prometheus",
			"customInlineTemplate": "PromQL:num_of_error_requests{scope=${scope}}",
			"serviceType": "prometheus"
		},
		"groups": [
			"error_requests"
		],
		"analysisConfigurations": {},
		"scopeName": "default"
	}]
```

I have also tried 

```
PromQL:num_of_error_requests\"{scope=${scope}}\"
PromQL:num_of_error_requests{scope=\"${scope}\"}
```

==============================================================

_Background: I am using ${} expressions since Prometheus internally depends on [FreeMarkerTemplateUtils](https://www.vogella.com/tutorials/FreeMarker/article.html) for its template bindings which use ${} expressions._

_**It puts my canary-baseline scope&location values in template bindings.**_

Reference:
[PrometheusMetricsService.java#L200](https://github.com/spinnaker/kayenta/blob/0e731ece68a9b873086718244030f71be633a8c9/kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java#L200)
[QueryConfigUtils.java#L99](https://github.com/spinnaker/kayenta/blob/0b40fc043cad705aa1f5fe155628d91089358c6c/kayenta-core/src/main/java/com/netflix/kayenta/canary/providers/metrics/QueryConfigUtils.java#L99)

==============================================================

But, ${} are being evaluated as part of orca pipeline expression evaluation logic in [ExpressionTransform.java](https://github.com/spinnaker/orca/blob/cd6b6cad218757a735e4b16d983127c2bc345a58/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java) before even reaching to PrometheusMetricsService.java 

Reference:
[ExpressionTransform.java#L135](https://github.com/spinnaker/orca/blob/cd6b6cad218757a735e4b16d983127c2bc345a58/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java#L135)

Hence, it Kayenta turns the **execution status** for canary analysis **TERMINAL** with the following error:

```
SERVER log.info():
c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:num_of_error_requests{scope=scope}), 1 failed - (PromQL:num_of_error_requests{scope=scope})

CLIENT RESPONSE:
"canaryExecutionResults": [
      {
        "executionId": "01DE9NXDD31K88FXCGE3QWSB6F",
        "executionStatus": "TERMINAL",
        "exception": {
          "details": {
            "errors": [
              "Failed to evaluate [my_template] : PromQL:num_of_error_requests{scope=scope} not found"
            ]
          }
        }
```

==========================================================

**Please provide any solution to correctly use Prometheus as my metric source.**

**Comment by duftler** [comment]
Should be resolved by: https://github.com/spinnaker/kayenta/pull/579

**Comment by amsin02** [comment]
Okay, I understood the format that it expects to escape expressions from orca evaluation
