### ISSUE TITLE
Canary sub-task exceptions not surfaced in top-level task

### ISSUE THREAD

**Issue by jtk54** [spinnaker/kayenta#588]
If a sub-task of the canary stage fails, the top-level task fails with a confusing error/exception message saying the canary passed:

![image](https://user-images.githubusercontent.com/5456773/61388140-6c252080-a885-11e9-9cca-c5b5f143bcd8.png)

Should change the messaging to surface the failure or at least not show the canary result as an exception.

**Comment by fieldju** [comment]
@maggieneterval is this an issue with Deck-Kayenta or with Kayenta not propagating the underlying errors properly? 

Could be related to: 
https://github.com/spinnaker/kayenta/issues/177
https://github.com/spinnaker/kayenta/issues/354

**Comment by maggieneterval** [comment]
@fieldju I'm guessing deck-kayenta. @jtk54 could you remind me what version of Spinnaker you're on? I _think_ @erikmunson fixed this (or something similar) very recently, but if not I can investigate!

**Comment by erikmunson** [comment]
Indeed, if you're not running HEAD I suspect this would fix your problem: https://github.com/spinnaker/deck-kayenta/pull/417

**Comment by maggieneterval** [comment]
Thanks for the fast reply @erikmunson! It looks like your change should be consumed by any version of Spinnaker 1.13 and later. @jtk54 let me know if we should close this once y'all can upgrade and confirm!

**Comment by fieldju** [comment]
Closing assuming https://github.com/spinnaker/deck-kayenta/pull/417 fixes issue.
