### ISSUE TITLE
[RFC] Proposed updates to the New Relic Insights metrics configuration to make the user experience less confusing.

### ISSUE THREAD

**Issue by fieldju** [spinnaker/kayenta#595]
The current way of configuring a New Relic Insights can be bit confusing for users to figure out.

Assume I have the following scope params

- scope: `myservice-prod-v01` 
- location: `us-west-2`

and the following extended Scope Parameters:

| Scope Key  | Scope Value |
| ------------- | ------------- |
| `_scope_key`  | asg_name |
| `_location_key`  | region |

Assume I want to create a New Relic insights query that gets the number of server errors for the following uri `/foo`, I would configure the following query for a metric as follows.

 
![image](https://user-images.githubusercontent.com/711726/61671371-31175880-ac9c-11e9-8e5e-d6a26b87ccbd.png)

```json
{
    "query": {
        "type": "newrelic",
        "select": "SELECT count(*) FROM Transactions",
        "q": "httpStatusCode like '5%' AND uri like '/foo'"
    }
}
```

This will produce the following query

```
SELECT count(*) 
FROM Transactions 
WHERE httpStatusCode like '5%' 
  AND uri like '/foo' 
  AND asg_name LIKE 'myservice-prod-v01' 
  AND region like 'us-west-2'
```

I think the original intent / goal was to have a flexible way of defining the queries that abstracted away NRQL.
It is a bit confusing to figure out how the pieces stitch together, because you still have to write out partial NRQL.

I propose we do the following (I am committing to do the work and make a PR).

I would like to essentially make this integration work more like the Prometheus integration where you can have inline templates or a simple abstracted user experience.

I essentially want the user experience in the UI to be choose from the following radio options

```
Select your query type:
- ( ) Simple
- ( ) Inline Template
```

If you select `Inline Template` the UI updates to just a single box labeled `NRQL` and where you could type something like the following 

```
SELECT count(*) 
FROM Transactions 
WHERE httpStatusCode like '5%' 
  AND uri like '/foo' 
  AND asg_name LIKE '${scope}' 
  AND region like '${location}'
```

![image](https://user-images.githubusercontent.com/711726/61671339-fdd4c980-ac9b-11e9-85fa-a2fcdcd12507.png)

This generates the following JSON

```json
{
    "query": {
      "type": "newrelic",
      "queryType": "inlineTemplate",
      "nrql": "SELECT count(*) FROM Transactions WHERE httpStatusCode like '5%' AND uri like '/foo' AND asg_name = '${scope} AND region = '${location}'"
    }   
}
```

If you select `Simple` you are presented with the following form fragment

```
Metric Name:        [ *            ]
Aggregation Method: [ count        ] <- Drop down menu with all options
Type:               [ Transactions ]
Filters:
    key: [ uri            ] Value [ /foo ] (delete)
    key: [ httpStatusCode ] Value [ 5%   ] (delete)
    
```

![image](https://user-images.githubusercontent.com/711726/61671348-0fb66c80-ac9c-11e9-900c-fd0b9ef3e84c.png)

This would produce the following JSON

```json
{
    "query": {
      "type": "newrelic",
      "queryType": "simple",
      "metricName": "*",
      "aggregationMethod": "count",
      "type": "Transactions",
      "filters": {
        "uri":"/foo",
        "httpStatusCode": "5%"
      },
    }   
}
```

CC: 
@imakewebthings
@ehmke 

## Proposal
I want to add at least the inline template flow.
I currently hypothesize that the Simple flow is useful, would love to hear thoughts on this.
I would love to rip out the current flow in favor of just using inline templates, but understand that could be tricky, we can keep the current logic as is and branch via conditionals as needed.

In addition to the above I also want to add `defaultScopeKey` and `defaultLocationKey` as done here for SignalFx: https://github.com/spinnaker/kayenta/pull/470

**Comment by ehmke** [comment]
As discussed on Slack, I find this good. I agree that the inline template flow is probably preferable over the query-concatenation we are doing right now.

**Comment by fieldju** [comment]
> As discussed on Slack, I find this good. I agree that the inline template flow is probably preferable over the query-concatenation we are doing right now.

I am going to abandon the Simple flow on the backend and just go with inline templates for now. That seems to be the user experience inside of New Relic insights that people are used to. I can implement the simple flow completely on the front end if people complain about the NRQL (I suspect this is unlikely).

**Comment by duftler** [comment]
I like it.

**Comment by fieldju** [comment]
> As discussed on Slack, I find this good. I agree that the inline template flow is probably preferable over the query-concatenation we are doing right now.

@ehmke the inline template stuff is additive, so the query concatenation is still there. 

I will probably use your `q` + `select` flow to enable the simple flow in the UI, but then allow users to just write inline templates if they choose via that radio checkbox.
