### ISSUE TITLE
New Relic aggregate functions don't work because returned values are in a different format

### ISSUE THREAD

**Issue by ehmke** [spinnaker/kayenta#597]
Submitted PR: https://github.com/spinnaker/kayenta/pull/596

This allows working with "percentile" aggregation function in NRQL.

**Comment by fieldju** [comment]
@ehmke, I am going to look into the inline template stuff today that we talked about in #595 and on slack.

Does #596 enable a user to write any NRQL that they want, or are there still constraints / gotchas?

**Comment by ehmke** [comment]
@fieldju It should work for queries which return simple values. The percentile function is able to return multiple values, because you can specify several percentiles to return in the same function. If other functions follow the same pattern, it could work work, however, I didn't try any on top of that. We are mostly using percentile-queries and some simple queries.
