### ISSUE TITLE
Outliers in metric results should not be removed by default

### ISSUE THREAD

**Issue by duftler** [spinnaker/kayenta#619]
Prior to the results being classified, outliers are currently removed. As the classification logic has for some time now been robust to outliers, there is no need to perform the pre-classification outlier removal.

Further, the removal of outliers can result in some unexpected results like a mean of zero when all non-zero values are determined to be outliers. When the control mean is zero, the result ratio will be NaN due to a divide-by-zero error. The reporting UI will then show the results as N/A.

As some folks perform offline experimentation using Kayenta as a library, we should add some configuration settings to allow them to explicitly re-enable the first pass outlier removal logic.

**Comment by csanden** [comment]
Thinking long term, I believe it would be valuable to turn outlier removal on and off for each metric via the metric configuration.
