### ISSUE TITLE
High value of deviation result passing incorrectly

### ISSUE THREAD

**Issue by silvez-dh** [spinnaker/kayenta#633]
A deviation result that calculates to a high value (+650% in this case) resulted in **PASS** whereas it must be **HIGH**

Examples for the same application running on different regions:

**Failed as expected:**
![failed1](https://user-images.githubusercontent.com/42961333/68386190-cfe89780-015b-11ea-8dce-6e3619f1dd55.png)

**Passed but should have failed:**
![failed2](https://user-images.githubusercontent.com/42961333/68386199-d6770f00-015b-11ea-9b9b-647e77e0fe5f.png)

**Spinnaker version:** 1.16.2
**Kayenta image:** gcr.io/spinnaker-marketplace/kayenta:0.11.0-20190830172818

**Comment by silvez-dh** [comment]
Issue still happens. Maybe @fieldju could take a look whenever have some time? Tks!

**Comment by silvez-dh** [comment]
@fieldju thanks for the reply, very appreciated. So to get more accurate results in this same same i would need to run canary for at least 50 min (to get enough datapoints)? Cheers

**Comment by fieldju** [comment]
Yes that, and I think you need to upgrade to 1.17 because of that outlier stuff.

**Comment by silvez-dh** [comment]
cool. Did it already. Providing some test right now to make sure the issue is gone. Tks once more!

**Comment by fieldju** [comment]
Please close the issue once you test is done.

Cheers,

Justin
