### ISSUE TITLE
feature request: teach kayenta to accept tags as part of canary config when using datadog

### ISSUE THREAD

**Issue by dbyron0** [spinnaker/kayenta#661]
### Cloud Provider(s):
Kubernetes v2

### Environment:
Datadog metrics

### Feature Area: 
Kayenta / automated canary analysis

### Description:
In a canary config for datadog, each metric query (i.e. the query object in each element of the metric array in the json) has a name e.g. `sum:requests.count`, but there isn't a way to specify tag:value pairs there.  These are tag:value pairs that are the same for both baseline and canary, that I'd like to share across canary analysis stages.

**Comment by fieldju** [comment]
Is this ticket closed by: https://github.com/spinnaker/kayenta/pull/657?

**Comment by dbyron0** [comment]
Yes, I believe you're right @fieldju .  Thanks much.
